#!/usr/bin/env bash
# =============================================================================
# lib/common.sh — Shared functions for pgbackup (pgBackRest edition)
# Source this file; do not execute directly.
# =============================================================================

set -euo pipefail

PGBACKUP_VERSION="${PGBACKUP_VERSION:-2.0.0}"

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
_log() {
    local level="$1"; shift
    local msg="$*"
    local ts; ts=$(date '+%Y-%m-%d %H:%M:%S')
    local line="[$ts] [$level] [${PROJECT_NAME:-pgbackup}] $msg"
    echo "$line"
    if [[ -n "${LOG_FILE:-}" ]]; then
        echo "$line" >> "$LOG_FILE" 2>/dev/null || true
    fi
}

log_info()  { [[ "${LOG_LEVEL:-INFO}" =~ ^(DEBUG|INFO)$ ]] && _log INFO  "$@" || true; }
log_debug() { [[ "${LOG_LEVEL:-INFO}" == "DEBUG" ]]         && _log DEBUG "$@" || true; }
log_warn()  { _log WARN  "$@"; }
log_error() { _log ERROR "$@" >&2; }

# ---------------------------------------------------------------------------
# Load project config + derive all paths
# ---------------------------------------------------------------------------
load_config() {
    local config_file="${1:-}"

    # Search default locations if not given
    if [[ -z "$config_file" ]]; then
        for f in \
            "/etc/pgbackup/${PROJECT_NAME:-}.env" \
            "./backup.env" \
            "../backup.env"; do
            [[ -f "$f" ]] && config_file="$f" && break
        done
    fi

    if [[ -z "$config_file" || ! -f "$config_file" ]]; then
        log_error "Config file not found. Pass --config /etc/pgbackup/<project>.env"
        exit 1
    fi

    # shellcheck source=/dev/null
    source "$config_file"
    CONFIG_FILE="$config_file"

    # Derived
    STANZA="$PROJECT_NAME"
    PGBACKREST_CONF="/etc/pgbackrest/pgbackrest-${PROJECT_NAME}.conf"
    LOG_FILE="${LOG_DIR:-/var/log/pgbackup}/${PROJECT_NAME}-$(date '+%Y-%m').log"

    export STANZA PGBACKREST_CONF CONFIG_FILE LOG_FILE
    export PGHOST="${PG_HOST}" PGPORT="${PG_PORT}" PGUSER="${PG_USER}"
}

# ---------------------------------------------------------------------------
# Generate pgBackRest config file for this project
# ---------------------------------------------------------------------------
write_pgbackrest_conf() {
    mkdir -p "$(dirname "$PGBACKREST_CONF")"

    {
        echo "# pgBackRest config for stanza: ${STANZA}"
        echo "# Generated by pgbackup — do not edit manually"
        echo "# Source of truth: ${CONFIG_FILE}"
        echo ""
        echo "[global]"
        echo "log-level-console=${LOG_LEVEL,,}"
        echo "log-level-file=${LOG_LEVEL,,}"
        echo "log-path=/var/log/pgbackrest"
        echo "compress-type=${COMPRESS_TYPE:-lz4}"
        echo "compress-level=${COMPRESS_LEVEL:-6}"
        echo "process-max=${PARALLEL_JOBS:-2}"
        echo "repo1-retention-full=${FULL_BACKUP_RETENTION:-2}"
        echo "repo1-retention-diff=${DIFF_BACKUP_RETENTION:-7}"
        echo "repo1-retention-archive=${WAL_RETENTION_DAYS:-7}"
        echo "repo1-retention-archive-type=diff"
        echo "start-fast=y"
        echo "delta=y"                    # Smart restore — only changed blocks

        # Repository type
        echo ""
        echo "# Repository"
        case "${REPO_TYPE:-posix}" in
            posix)
                echo "repo1-type=posix"
                echo "repo1-path=${REPO_PATH}"
                ;;
            s3)
                echo "repo1-type=s3"
                echo "repo1-path=/"
                echo "repo1-s3-bucket=${REPO_S3_BUCKET}"
                echo "repo1-s3-region=${REPO_S3_REGION}"
                [[ -n "${REPO_S3_ENDPOINT:-}" ]] && echo "repo1-s3-endpoint=${REPO_S3_ENDPOINT}"
                [[ -n "${REPO_S3_KEY:-}" ]]      && echo "repo1-s3-key=${REPO_S3_KEY}"
                [[ -n "${REPO_S3_KEY_SECRET:-}" ]] && echo "repo1-s3-key-secret=${REPO_S3_KEY_SECRET}"
                ;;
            gcs)
                echo "repo1-type=gcs"
                echo "repo1-path=/"
                echo "repo1-gcs-bucket=${REPO_GCS_BUCKET}"
                echo "repo1-gcs-key=${REPO_GCS_KEY}"
                ;;
        esac

        # Encryption
        if [[ "${ENCRYPT_ENABLED:-false}" == "true" ]]; then
            echo ""
            echo "# Encryption"
            echo "repo1-cipher-type=aes-256-cbc"
            echo "repo1-cipher-pass=${ENCRYPT_PASSPHRASE}"
        fi

        # Stanza (one per project)
        echo ""
        echo "[${STANZA}]"
        echo "pg1-path=${PG_DATA_DIR}"
        echo "pg1-host=${PG_HOST}"
        echo "pg1-port=${PG_PORT}"
        echo "pg1-user=${PG_USER}"

    } > "$PGBACKREST_CONF"

    chmod 640 "$PGBACKREST_CONF"
    log_debug "pgBackRest config written: $PGBACKREST_CONF"
}

# ---------------------------------------------------------------------------
# Run pgbackrest with project config
# ---------------------------------------------------------------------------
pgbr() {
    pgbackrest --config="$PGBACKREST_CONF" --stanza="$STANZA" "$@"
}

# ---------------------------------------------------------------------------
# Ensure dirs exist
# ---------------------------------------------------------------------------
ensure_dirs() {
    mkdir -p \
        "${LOG_DIR:-/var/log/pgbackup}" \
        /var/log/pgbackrest \
        /etc/pgbackrest

    if [[ "${REPO_TYPE:-posix}" == "posix" ]]; then
        mkdir -p "$REPO_PATH"
        chmod 750 "$REPO_PATH"
    fi
}

# ---------------------------------------------------------------------------
# Postgres connectivity check
# ---------------------------------------------------------------------------
check_postgres() {
    log_info "Checking PostgreSQL connectivity..."
    if ! psql -h "$PG_HOST" -p "$PG_PORT" -U "$PG_USER" \
              -d "${PG_DATABASE:-postgres}" -c "SELECT 1" \
              -q --tuples-only > /dev/null 2>&1; then
        log_error "Cannot connect to PostgreSQL at ${PG_HOST}:${PG_PORT}"
        return 1
    fi
    log_info "PostgreSQL connection OK"
}

# ---------------------------------------------------------------------------
# Dependency check
# ---------------------------------------------------------------------------
check_deps() {
    local missing=()
    for cmd in pgbackrest psql; do
        command -v "$cmd" &>/dev/null || missing+=("$cmd")
    done
    if [[ ${#missing[@]} -gt 0 ]]; then
        log_error "Missing required commands: ${missing[*]}"
        log_error "Install pgBackRest: https://pgbackrest.org/user-guide.html#installation"
        exit 1
    fi
    log_debug "Dependencies OK (pgbackrest $(pgbackrest version | head -1))"
}

# ---------------------------------------------------------------------------
# Lock file
# ---------------------------------------------------------------------------
LOCK_FILE="/tmp/pgbackup_${PROJECT_NAME:-default}.lock"

acquire_lock() {
    if [[ -f "$LOCK_FILE" ]]; then
        local pid; pid=$(cat "$LOCK_FILE")
        if kill -0 "$pid" 2>/dev/null; then
            log_error "Another backup is already running (PID $pid). Exiting."
            exit 1
        fi
        log_warn "Stale lock file found, removing."
        rm -f "$LOCK_FILE"
    fi
    echo $$ > "$LOCK_FILE"
    trap 'rm -f "$LOCK_FILE"' EXIT
}

# ---------------------------------------------------------------------------
# Alerting
# ---------------------------------------------------------------------------
send_alert() {
    local subject="$1"
    local body="${2:-}"

    log_warn "ALERT: $subject"

    if [[ -n "${ALERT_EMAIL:-}" ]] && command -v mail &>/dev/null; then
        echo "$body" | mail -s "[pgbackup] $subject" "$ALERT_EMAIL" || true
    fi

    if [[ -n "${SLACK_WEBHOOK_URL:-}" ]] && command -v curl &>/dev/null; then
        local payload
        payload=$(printf '{"text":"🚨 *[pgbackup/%s]* %s\n```%s```"}' \
                  "$PROJECT_NAME" "$subject" "$body")
        curl -s -X POST -H 'Content-type: application/json' \
             --data "$payload" "$SLACK_WEBHOOK_URL" > /dev/null || true
    fi
}

# ---------------------------------------------------------------------------
# Elapsed time
# ---------------------------------------------------------------------------
elapsed_since() {
    echo $(( $(date +%s) - $1 ))
}
